### ISSUE TITLE
RuntimeError: The size of tensor a (512) must match the size of tensor b (37) at non-singleton dimension 0

### ISSUE THREAD

**Issue by OedoSoldier** [ssbuild/chatglm_finetuning#1]
Parameters:

```
train_info_args = {
    'devices': 1,
    'data_backend': 'record',
    'model_type': 'chatglm',
    # 预训练模型路径 , 从0训练，则置空
    'model_name_or_path': '../chatglm_webui_dev/chatglm-6b',
    'config_name': './config/config_small.json',
    'tokenizer_name': '../chatglm_webui_dev/chatglm-6b',
    'convert_onnx': False, # 转换onnx模型
    'do_train': True,
    'train_file':  [ './data/processed_alpaca_data.json'],
    'max_epochs': 3,
    'max_steps': -1,
    'optimizer': 'lion', # one of adamw,adam,lamb,lion
    'train_batch_size': 128,
    'eval_batch_size': 2,
    'test_batch_size': 2,
    'learning_rate': 2e-5,
    'adam_epsilon': 1e-8,
    'gradient_accumulation_steps': 1,
    'max_grad_norm': 1.0,
    'weight_decay': 1.0,
    'warmup_steps': 0,
    'output_dir': './output',
    'max_seq_length': 512,
    'max_target_length': 512,  # 预测最大长度
    'use_fast_tokenizer': False,
    'do_lower_case': False,
}
```

```
{
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 1,
  "position_encoding_2d": true,
  "torch_dtype": "float16",
  "transformers_version": "4.23.1",
  "use_cache": true,
  "vocab_size": 150528,
  "precision": 16
}
```

Error:
```
Traceback (most recent call last):
  File "F:\python\llm\chatglm_finetuning\train.py", line 160, in <module>
    trainer.fit(model, train_dataloaders=train_datasets)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1166, in _run
    results = self._run_stage()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\core\module.py", line 1705, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\core\optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\optimizer\lion\lion.py", line 72, in step
    loss = closure()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 132, in closure
    step_output = self._step_fn()
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 407, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 564, in training_step
    outputs = self.compute_loss(**batch)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 395, in compute_loss
    return self.model.compute_loss(**kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 141, in compute_loss
    return self.model(*args,**batch)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 1038, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 886, in forward
    layer_ret = layer(
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 575, in forward
    attention_outputs = self.attention(
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 418, in forward
    q1, k1 = apply_rotary_pos_emb_index(q1, k1, cos, sin, position_ids)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 199, in <fused code>
        F.embedding(position_id, sin.squeeze(1)).unsqueeze(2)
    q = (q * cos) + (rotate_half(q) * sin)
    k = (k * cos) + (rotate_half(k) * sin)
         ~~~~~~~ <--- HERE
    return q, k
RuntimeError: The size of tensor a (512) must match the size of tensor b (37) at non-singleton dimension 0
```

**Comment by Oyaxira** [comment]
一样的问题,有解么?

**Comment by ssbuild** [comment]
> 一样的问题,有解么?

已更新，当前状态测试通过

**Comment by ssbuild** [comment]
> Parameters:
> 
> ```
> train_info_args = {
>     'devices': 1,
>     'data_backend': 'record',
>     'model_type': 'chatglm',
>     # 预训练模型路径 , 从0训练，则置空
>     'model_name_or_path': '../chatglm_webui_dev/chatglm-6b',
>     'config_name': './config/config_small.json',
>     'tokenizer_name': '../chatglm_webui_dev/chatglm-6b',
>     'convert_onnx': False, # 转换onnx模型
>     'do_train': True,
>     'train_file':  [ './data/processed_alpaca_data.json'],
>     'max_epochs': 3,
>     'max_steps': -1,
>     'optimizer': 'lion', # one of adamw,adam,lamb,lion
>     'train_batch_size': 128,
>     'eval_batch_size': 2,
>     'test_batch_size': 2,
>     'learning_rate': 2e-5,
>     'adam_epsilon': 1e-8,
>     'gradient_accumulation_steps': 1,
>     'max_grad_norm': 1.0,
>     'weight_decay': 1.0,
>     'warmup_steps': 0,
>     'output_dir': './output',
>     'max_seq_length': 512,
>     'max_target_length': 512,  # 预测最大长度
>     'use_fast_tokenizer': False,
>     'do_lower_case': False,
> }
> ```
> 
> ```
> {
>   "architectures": [
>     "ChatGLMModel"
>   ],
>   "auto_map": {
>     "AutoConfig": "configuration_chatglm.ChatGLMConfig",
>     "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
>     "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
>   },
>   "bos_token_id": 150004,
>   "eos_token_id": 150005,
>   "hidden_size": 4096,
>   "inner_hidden_size": 16384,
>   "layernorm_epsilon": 1e-05,
>   "max_sequence_length": 2048,
>   "model_type": "chatglm",
>   "num_attention_heads": 32,
>   "num_layers": 1,
>   "position_encoding_2d": true,
>   "torch_dtype": "float16",
>   "transformers_version": "4.23.1",
>   "use_cache": true,
>   "vocab_size": 150528,
>   "precision": 16
> }
> ```
> 
> Error:
> 
> ```
> Traceback (most recent call last):
>   File "F:\python\llm\chatglm_finetuning\train.py", line 160, in <module>
>     trainer.fit(model, train_dataloaders=train_datasets)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 696, in fit
>     self._call_and_handle_interrupt(
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 735, in _fit_impl
>     results = self._run(model, ckpt_path=self.ckpt_path)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1166, in _run
>     results = self._run_stage()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1252, in _run_stage
>     return self._run_train()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1283, in _run_train
>     self.fit_loop.run()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 271, in advance
>     self._outputs = self.epoch_loop.run(self._data_fetcher)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 203, in advance
>     batch_output = self.batch_loop.run(kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 87, in advance
>     outputs = self.optimizer_loop.run(optimizers, kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 201, in advance
>     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 248, in _run_optimization
>     self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 358, in _optimizer_step
>     self.trainer._call_lightning_module_hook(
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1550, in _call_lightning_module_hook
>     output = fn(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\core\module.py", line 1705, in optimizer_step
>     optimizer.step(closure=optimizer_closure)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\core\optimizer.py", line 168, in step
>     step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 216, in optimizer_step
>     return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 153, in optimizer_step
>     return optimizer.step(closure=closure, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
>     return wrapped(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
>     out = func(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\optimizer\lion\lion.py", line 72, in step
>     loss = closure()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 138, in _wrap_closure
>     closure_result = closure()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 146, in __call__
>     self._result = self.closure(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 132, in closure
>     step_output = self._step_fn()
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py", line 407, in _training_step
>     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1704, in _call_strategy_hook
>     output = fn(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 358, in training_step
>     return self.model.training_step(*args, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 564, in training_step
>     outputs = self.compute_loss(**batch)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 395, in compute_loss
>     return self.model.compute_loss(**kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\transformer.py", line 141, in compute_loss
>     return self.model(*args,**batch)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 1038, in forward
>     transformer_outputs = self.transformer(
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 886, in forward
>     layer_ret = layer(
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 575, in forward
>     attention_outputs = self.attention(
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 418, in forward
>     q1, k1 = apply_rotary_pos_emb_index(q1, k1, cos, sin, position_ids)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File "C:\Users\wangs\anaconda3\envs\sd\lib\site-packages\deep_training\nlp\models\chatglm\__init__.py", line 199, in <fused code>
>         F.embedding(position_id, sin.squeeze(1)).unsqueeze(2)
>     q = (q * cos) + (rotate_half(q) * sin)
>     k = (k * cos) + (rotate_half(k) * sin)
>          ~~~~~~~ <--- HERE
>     return q, k
> RuntimeError: The size of tensor a (512) must match the size of tensor b (37) at non-singleton dimension 0
> ```

已更新，当前状态测试通过

**Comment by hpsun1109** [comment]
请问这个是怎么解决的，之前其他代码遇到过相同的问题

**Comment by hpsun1109** [comment]
> > 一样的问题,有解么? @OedoSoldier @Oyaxira
> 
> 已更新，当前状态测试通过
请问这个是怎么解决的，之前其他代码遇到过相同的问题

**Comment by hpsun1109** [comment]
> > 一样的问题,有解么? @OedoSoldier @Oyaxira
> 
> 已更新，当前状态测试通过


请问这个是怎么解决的，之前其他代码遇到过相同的问题
