### ISSUE TITLE
无法加载数据，是不是python版本不对？

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [ssbuild/chatglm_finetuning#109]
INFO:root:load dataset to memory...
Traceback (most recent call last):
  File "/chatglm_finetuning/train.py", line 167, in <module>
    train_datasets = dataHelper.load_random_sampler(dataHelper.train_files,
  File "/usr/local/lib/python3.10/site-packages/deep_training/data_helper/data_helper.py", line 472, in load_random_sampler
    return DataLoader(dataset,batch_size=batch_size,
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by ssbuild** [comment]
删除output文件夹，redo

**Comment by xiaoyaolangzhi** [comment]
> 删除output文件夹，redo

找到问题了，数据只有2条不行，我改成4条就可以了，多谢！
