### ISSUE TITLE
想问一下，是否可以指定在某一张卡训练，其他卡显存都被占满了

### ISSUE THREAD

**Issue by Starsoul233** [ssbuild/chatglm_finetuning#134]

**Comment by ssbuild** [comment]
可以， 例如  devices =[1]  ， 即第二张卡。

**Comment by Starsoul233** [comment]
> 

想确认一下是在data_utils.py改吧？如果是的话我这边报错了，`  File "/home/chatglm_finetuning/train.py", line 167, in <module>
    train_datasets = dataHelper.load_random_sampler(dataHelper.train_files,
  File "/root/miniconda3/envs/glm_finetune/lib/python3.10/site-packages/deep_training/data_helper/data_helper.py", line 460, in load_random_sampler
    dataset = self.load_dataset(
  File "/root/miniconda3/envs/glm_finetune/lib/python3.10/site-packages/deep_training/data_helper/data_helper.py", line 385, in load_dataset
    dataset = self.load_numpy_dataset(files,
  File "/root/miniconda3/envs/glm_finetune/lib/python3.10/site-packages/deep_training/data_helper/data_helper.py", line 353, in load_numpy_dataset
    dataset = dataset_loader_filter_fn(dataset)
  File "/home/chatglm_finetuning/train.py", line 163, in dataset_loader_filter_fn
    limit_count = int(limit_count // (data_args.devices * training_args.train_batch_size * host_num)) * (data_args.devices * training_args.train_batch_size * host_num)
TypeError: unsupported operand type(s) for //: 'int' and 'list'`

**Comment by Starsoul233** [comment]
解决了，谢谢大佬

**Comment by Starsoul233** [comment]
> > unsupported
> 
> 这个是为了保证数据满batch的一个限制，拉下新代码吧，新代码用了分布式datasets 去掉了这个限制， 或者手段修该函数。

解决了，谢谢大佬

**Comment by Starsoul233** [comment]
> > unsupported
> 
> 这个是为了保证数据满batch的一个限制，拉下新代码吧，新代码用了分布式datasets 去掉了这个限制， 或者手段修该函数。

pull新代码运行之后又出现了这个错误`Traceback (most recent call last):
  File "/home/chatglm_finetuning/train.py", line 165, in <module>
    train_datasets = dataHelper.load_distributed_random_sampler(
AttributeError: 'NN_DataHelper' object has no attribute 'load_distributed_random_sampler'`

**Comment by ssbuild** [comment]
pip install -i https://pypi.org/simple -U deep_training>=0.1.0
