### ISSUE TITLE
运行api_lora_demo.py报错

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#144]
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpdk6mpo7h
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpdk6mpo7h/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/root/zysdata/alpaca_chinese_dataset-main_finaled/chatglm_finetuning-main20230328/api_lora.py", line 73, in <module>
    tokenizer, _, _, _ = dataHelper.load_tokenizer_and_config(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/data_helper/data_helper.py", line 257, in load_tokenizer_and_config
    tokenizer = load_tokenizer(tokenizer_name=tokenizer_name or model_args.tokenizer_name,
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/data_helper/data_module.py", line 29, in load_tokenizer
    tokenizer = class_name.from_pretrained(tokenizer_name, **tokenizer_kwargs)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './models'.

**Comment by ssbuild** [comment]
检查下data_utils.py  train_info_args   模型等路径

**Comment by cristianohello** [comment]
@ssbuild 
我是用的领域数据微调的lora模型。
又报错？
官方的api.py加载不报错。但是加载lora后的best_ckpt就报错？


TrainingArguments(optimizer='lion', scheduler_type='linear', scheduler=None, adv={'mode': None, 'emb_name=': 'embedding', 'attack_iters': 2, 'minibatch_replays': 2, 'alpha': 0.1, 'epsilon': 1.0}, hierarchical_position=None, learning_rate=2e-06, learning_rate_for_task=2e-06, max_epochs=10, max_steps=-1, optimizer_betas=(0.9, 0.999), adam_epsilon=1e-08, gradient_accumulation_steps=1, max_grad_norm=1.0, weight_decay=0, warmup_steps=0, train_batch_size=4, eval_batch_size=2, test_batch_size=2, seed=None)
ModelArguments(model_name_or_path='./models', model_type='chatglm', config_overrides=None, config_name='./config/config.json', tokenizer_name='./models', cache_dir=None, do_lower_case=False, use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:08<00:00,  1.09s/it]
****************************** lora info
trainable params: 58720256 || all params: 6930489344 || trainable%: 0.8472743133331048
Traceback (most recent call last):
  File "/root/zysdata/alpaca_chinese_dataset-main_finaled/chatglm_finetuning-main20230328/api_lora.py", line 91, in <module>
    model.half().to(torch.cuda.device(CUDA_DEVICE))
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/torch/nn/modules/module.py", line 968, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
TypeError: to() received an invalid combination of arguments - got (device), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)

**Comment by cristianohello** [comment]
@ssbuild 


现在这个报错：

TrainingArguments(optimizer='lion', scheduler_type='linear', scheduler=None, adv={'mode': None, 'emb_name=': 'embedding', 'attack_iters': 2, 'minibatch_replays': 2, 'alpha': 0.1, 'epsilon': 1.0}, hierarchical_position=None, learning_rate=2e-06, learning_rate_for_task=2e-06, max_epochs=10, max_steps=-1, optimizer_betas=(0.9, 0.999), adam_epsilon=1e-08, gradient_accumulation_steps=1, max_grad_norm=1.0, weight_decay=0, warmup_steps=0, train_batch_size=4, eval_batch_size=2, test_batch_size=2, seed=None)
ModelArguments(model_name_or_path='./models', model_type='chatglm', config_overrides=None, config_name='./config/config.json', tokenizer_name='./models', cache_dir=None, do_lower_case=False, use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.16s/it]
^CTraceback (most recent call last):
  File "/root/zysdata/alpaca_chinese_dataset-main_finaled/chatglm_finetuning-main20230328/api_lora.py", line 84, in <module>
    pl_model = MyTransformer(config=config, model_args=model_args, training_args=training_args, lora_args=lora_args)
  File "/root/zysdata/alpaca_chinese_dataset-main_finaled/chatglm_finetuning-main20230328/models.py", line 72, in __init__
    model = LoraModel(self.backbone, lora_args)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/nlp/models/lora/__init__.py", line 94, in __init__
    self._find_and_replace()
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/nlp/models/lora/__init__.py", line 148, in _find_and_replace
    new_module = Linear(target.in_features, target.out_features, bias=bias, **kwargs)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/nlp/layers/lora/layers.py", line 114, in __init__
    nn.Linear.__init__(self, in_features, out_features, **kwargs)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 101, in __init__
    self.reset_parameters()
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/deep_training/nlp/layers/lora/layers.py", line 131, in reset_parameters
    nn.Linear.reset_parameters(self)
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 107, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/torch/nn/init.py", line 412, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
**KeyboardInterrupt**

**Comment by ssbuild** [comment]
已更新api_lora_demo.py ， try it.

**Comment by ssbuild** [comment]
> 

这个错误是你刚才改动哪里出现的？

**Comment by cristianohello** [comment]
@ssbuild 
可以了！更新最新代码就可以了！速度很快！太牛啦！马上用在生产环境上

**Comment by cristianohello** [comment]
@ssbuild 
太牛啦！
