### ISSUE TITLE
AttributeError: 'Tqdm' object has no attribute '_time' 

### ISSUE THREAD

**Issue by leoluopy** [ssbuild/chatglm_finetuning#183]
error occurs :
 AttributeError: 'Tqdm' object has no attribute '_time' 

when : [ devices = 2]
train_info_args = {
    'devices': 2,
    'data_backend': 'record',
    'model_type': 'chatglm',
    # 预训练模型路径 , 从0训练，则置空
    'model_name_or_path': '/home/e0004587/Downloads/chatglm-6b/',

how to fix it ?

**Comment by ssbuild** [comment]
上传更多一些错误日志信息。

**Comment by leoluopy** [comment]
Epoch 0:   3%|████▉                                                                                                                                                                                   | 1/37 [00:01<01:10,  1.97s/it]Traceback (most recent call last):
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 198, in run
    self.on_advance_start(*args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 248, in on_advance_start
    self.trainer._call_callback_hooks("on_train_epoch_start")
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1394, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/tqdm_progress.py", line 256, in on_train_epoch_start
    self.main_progress_bar.reset(convert_inf(total_batches))
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/tqdm/std.py", line 1402, in reset
    self.last_print_t = self.start_t = self._time()
AttributeError: 'Tqdm' object has no attribute '_time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/algo_share/projects/peiyuanluo/workspace/chatglm_finetuning/train.py", line 180, in <module>
    trainer.fit(pl_model, train_dataloaders=train_datasets)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt
    trainer.strategy.reconciliate_processes(traceback.format_exc())
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 460, in reconciliate_processes
    raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \n {trace}")
pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 1 
 Traceback (most recent call last):
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 198, in run
    self.on_advance_start(*args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 248, in on_advance_start
    self.trainer._call_callback_hooks("on_train_epoch_start")
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1394, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/tqdm_progress.py", line 256, in on_train_epoch_start
    self.main_progress_bar.reset(convert_inf(total_batches))
  File "/home/e0004587/.pyenv/versions/anaconda3-2020.11/lib/python3.8/site-packages/tqdm/std.py", line 1402, in reset
    self.last_print_t = self.start_t = self._time()
AttributeError: 'Tqdm' object has no attribute '_time'

**Comment by ssbuild** [comment]
参考 https://github.com/tqdm/tqdm/issues/1125
这种问题通常升级 相应的模块即可解决。
