### ISSUE TITLE
整体ft的时候报错，大家有遇到的嘛 RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by heiheiwangergou** [ssbuild/chatglm_finetuning#188]
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    trainer.fit(pl_model, train_dataloaders=train_datasets)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 978, in _run_stage
    self.fit_loop.run()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 261, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 142, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1265, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 158, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 224, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 114, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/optimizer/lion/lion.py", line 72, in step
    loss = closure()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 101, in _wrap_closure
    closure_result = closure()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 308, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 366, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 529, in training_step
    outputs = self.compute_loss(**batch)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 360, in compute_loss
    return self.model.compute_loss(**kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 119, in compute_loss
    return self.model(*args,**batch)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1191, in forward
    transformer_outputs = self.transformer(
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1010, in forward
    layer_ret = layer(
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 618, in forward
    attention_input = self.input_layernorm(hidden_states)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/home/miniconda3/envs/chatglm_finetuning/lib/python3.8/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
Epoch 0:   0%|          | 0/39 [00:09<?, ?it/s]

**Comment by ssbuild** [comment]
关于精度都改了哪些地方？
