### ISSUE TITLE
python train.py执行训练报错，求解。

### ISSUE THREAD

**Issue by pan365wang** [ssbuild/chatglm_finetuning#214]
INFO:lightning_fabric.utilities.seed:Global seed set to 42
<__main__.MySimpleModelCheckpoint object at 0x0000026F7A73C610>
Traceback (most recent call last):
  File "D:\vmware\chat_zhenhuan\train.py", line 103, in <module>
    trainer = Trainer(
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 421, in __init__
    self._callback_connector.on_trainer_init(
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py", line 79, in on_trainer_init
    _validate_callbacks_list(self.trainer.callbacks)
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py", line 252, in _validate_callbacks_list
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py", line 252, in <listcomp>
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\Admin\.conda\envs\py310\lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 34, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent

**Comment by ssbuild** [comment]
pytorch_lightning 改名  lightning 了，使用 dev 仓库代码 
或者自行降低 deep_training == 0.1.2

**Comment by ruleGreen** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/26263128/236977668-746c8909-5a2b-4f0d-aa2b-6fed7a2fd5d5.png">
请问这个是什么原因？dev和stable代码都试过了

**Comment by ruleGreen** [comment]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/26263128/236977814-23f988c5-ca69-4a14-94bd-da6781d2b180.png">

**Comment by ssbuild** [comment]
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/26263128/236977814-23f988c5-ca69-4a14-94bd-da6781d2b180.png">

词典权重精简一次，从抱抱脸重新下载一份权重，

**Comment by ruleGreen** [comment]
> > <img alt="image" width="337" src="https://user-images.githubusercontent.com/26263128/236977814-23f988c5-ca69-4a14-94bd-da6781d2b180.png">
> 
> 词典权重精简一次，从抱抱脸重新下载一份权重，

的确是这个问题，忘记同步了，但是我遇到了另外一个问题类似于 https://github.com/ssbuild/chatglm_finetuning/issues/146
参考
> lora int8 多卡训练 CUDA_VISIBLE_DEVICES=显卡数量 和 data_utils.py devices 保持一致，否则容易出故障 ， 建议使用 CUDA_VISIBLE_DEVICES=显卡数量 python train.py , 或者使用docker隔离环境。

我的lora int8 单机多卡训练还是有错误，我设置devices=2, 然后CUDA_VISIBLE_DEVICES=1,2 python train.py 这样

**Comment by ssbuild** [comment]
#146 @ruleGreen

**Comment by peng913** [comment]
Traceback (most recent call last):
  File "/home/tom/SAFARI-master/SAFARI-master/lora/scripts/../infer.py", line 10, in <module>
    from tools.retriever import *
ModuleNotFoundError: No module named 'tools.retriever'请问这个错误是tools包的导入问题吗

**Comment by ssbuild** [comment]
> Traceback (most recent call last): File "/home/tom/SAFARI-master/SAFARI-master/lora/scripts/../infer.py", line 10, in from tools.retriever import * ModuleNotFoundError: No module named 'tools.retriever'请问这个错误是tools包的导入问题吗

你的代码不是本仓库的吧， 没有引用tools 包

**Comment by peng913** [comment]
是本仓库的，我不知道从那方面开始入手复现这个实验，于是就乱跑Lora包中的scripts脚本于是就开始报错了
