### ISSUE TITLE
使用config.json参数进行finetune，loss为nan

### ISSUE THREAD

**Issue by Lisa976** [ssbuild/chatglm_finetuning#30]
使用昨日最新拉取代码及config.json大参数进行finetune，训练到1/5报错loss为nan。麻烦看一下是训练代码不稳定还是操作问题导致，谢谢。

Epoch 0:  19%|█▉        | 2013/10572 [3:51:13<16:23:08,  6.89s/it, loss=nan, v_num=11]Using /home/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Loading extension module utils...
Using /home/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.4044802188873291 seconds
Rank: 2 partition count [4, 4] and sizes[(1563485184, False), (316416, False)] 
Time to load utils op: 0.0005748271942138672 seconds
Traceback (most recent call last):
  File "/chatglm_finetuning-main/train.py", line 183, in <module>
    trainer.fit(model, train_dataloaders=train_datasets)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1742, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 280, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/deepspeed.py", line 142, in optimizer_step
    return deepspeed_engine.step(**kwargs)
  File "/home/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 2168, in step
    self._take_model_step(lr_kwargs)
  File "/home/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 2070, in _take_model_step
    self.optimizer.step()
  File "/home/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1788, in step
    self._update_scale(self.overflow)
  File "/home/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2045, in _update_scale
    self.loss_scaler.update_scale(has_overflow)
  File "/home/.local/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 156, in update_scale
    raise Exception(
Exception: Current loss scale already at minimum - cannot decrease scale anymore. Exiting run.

**Comment by ssbuild** [comment]
please upload your config

**Comment by Lisa976** [comment]
config:
{
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "position_encoding_2d": true,
  "torch_dtype": "float16",
  "transformers_version": "4.23.1",
  "use_cache": true,
  "vocab_size": 150528,
  "precision": 16
}

train_info_args = {
    'devices': 4,
    'data_backend': 'record',
    'model_type': 'chatglm',
    # 预训练模型路径 , 从0训练，则置空
    'model_name_or_path': '/chatglm-6b',
    'config_name': './config/config.json',
    'tokenizer_name': '/chatglm-6b',
    'convert_onnx': False, # 转换onnx模型
    'do_train': True,
    'train_file':  [ './data/train.json'],
    'max_epochs': 8,
    'max_steps': -1,
    'optimizer': 'lion', # one of adamw,adam,lamb,lion
    'train_batch_size': 4,
    'eval_batch_size': 2,
    'test_batch_size': 2,
    'learning_rate': 5e-5,
    'adam_epsilon': 1e-8,
    'gradient_accumulation_steps': 1,
    'max_grad_norm': 1.0,
    'weight_decay': 0,
    'warmup_steps': 0,
    'output_dir': './output',
    'max_seq_length': 512,
    'max_target_length': 512,  # 预测最大长度
    'use_fast_tokenizer': False,
    'do_lower_case': False,
    ##############  lora模块
    'with_lora': False,  # 是否启用lora模块
    'inference_mode': False,
    'r': 8,
    'target_modules': ['query_key_value'],
    'target_dtype': '16',
    'lora_alpha': 32,
    # 'enable_lora': [True],
    'enable_lora': None,
    'lora_dropout': 0.1,
    'bias': 'none',  # Bias type for Lora. Can be 'none', 'all' or 'lora_only'"
}

#lora 模式暂时不支持deepspeed
enable_deepspeed = True

**Comment by ssbuild** [comment]
> config: { "architectures": [ "ChatGLMModel" ], "auto_map": { "AutoConfig": "configuration_chatglm.ChatGLMConfig", "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration", "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration" }, "bos_token_id": 150004, "eos_token_id": 150005, "hidden_size": 4096, "inner_hidden_size": 16384, "layernorm_epsilon": 1e-05, "max_sequence_length": 2048, "model_type": "chatglm", "num_attention_heads": 32, "num_layers": 28, "position_encoding_2d": true, "torch_dtype": "float16", "transformers_version": "4.23.1", "use_cache": true, "vocab_size": 150528, "precision": 16 }
> 
> train_info_args = { 'devices': 4, 'data_backend': 'record', 'model_type': 'chatglm', # 预训练模型路径 , 从0训练，则置空 'model_name_or_path': '/chatglm-6b', 'config_name': './config/config.json', 'tokenizer_name': '/chatglm-6b', 'convert_onnx': False, # 转换onnx模型 'do_train': True, 'train_file': [ './data/train.json'], 'max_epochs': 8, 'max_steps': -1, 'optimizer': 'lion', # one of adamw,adam,lamb,lion 'train_batch_size': 4, 'eval_batch_size': 2, 'test_batch_size': 2, 'learning_rate': 5e-5, 'adam_epsilon': 1e-8, 'gradient_accumulation_steps': 1, 'max_grad_norm': 1.0, 'weight_decay': 0, 'warmup_steps': 0, 'output_dir': './output', 'max_seq_length': 512, 'max_target_length': 512, # 预测最大长度 'use_fast_tokenizer': False, 'do_lower_case': False, ############## lora模块 'with_lora': False, # 是否启用lora模块 'inference_mode': False, 'r': 8, 'target_modules': ['query_key_value'], 'target_dtype': '16', 'lora_alpha': 32, # 'enable_lora': [True], 'enable_lora': None, 'lora_dropout': 0.1, 'bias': 'none', # Bias type for Lora. Can be 'none', 'all' or 'lora_only'" }
> 
> #lora 模式暂时不支持deepspeed enable_deepspeed = True

调小学习率 或者 更换优化器 ， 或者二者灵活调整试试。

**Comment by acadaiaca** [comment]
我遇到了同样的问题， @ssbuild 请问训练过程有tensorboard或者wandb可视化吗？
其它参数使用的是默认的，尝试换了adam优化器，以及调小学习率至1e-5，1e-6，1e-8，loss都报nan

**Comment by ssbuild** [comment]
> Reference in new issue

参数不对吧， 支持tensorboard 进output 子目录

**Comment by acadaiaca** [comment]
尝试了num_layers=1或16等等小于28的情况，调大或调小学习率或更换优化器，loss依然总是报nan
让num_layers=28，学习率随便设的2e-5，优化器设的amamw，没有去特意调参数，loss恢复了正常，降到了1点几

**Comment by Syno8** [comment]
@Lisa976 @ssbuild @acadaiaca hi, 我刚也试了一下这个问题，然后发现，你们有用deepspeed 吗？有这个问题吗？

```
  File "deepspeed/runtime/zero/stage_1_and_2.py", line 2096, in _get_base_optimizer_state
    lean_optimizer_state = self._get_state_without_padding(
  File "deepspeed/runtime/zero/stage_1_and_2.py", line 2084, in _get_state_without_padding
    lean_state[key] = value[:lean_length]
IndexError: slice() cannot be applied to a 0-dim tensor.
```

**Comment by acadaiaca** [comment]
> @Lisa976 @ssbuild @acadaiaca hi, 我刚也试了一下这个问题，然后发现以下问题，你们有用deepspeed 吗？有这个问题吗？
> 
> ```
>   File "deepspeed/runtime/zero/stage_1_and_2.py", line 2096, in _get_base_optimizer_state
>     lean_optimizer_state = self._get_state_without_padding(
>   File "deepspeed/runtime/zero/stage_1_and_2.py", line 2084, in _get_state_without_padding
>     lean_state[key] = value[:lean_length]
> IndexError: slice() cannot be applied to a 0-dim tensor.
> ```

是的，用了deepspeed，计算完一个epoch之后现在也遇到了这个问题

**Comment by gg22mm** [comment]
我发现loss为nan是针对有些机子或是显示存在，同一套代码，在 k80是显示nan, 在GeForce RTX3090 上显示正常，配置用的是：./config/config_small.json

**Comment by Syno8** [comment]
调整一下参数
