### ISSUE TITLE
单机多卡训练问题

### ISSUE THREAD

**Issue by paulcx** [ssbuild/chatglm_finetuning#47]
使用deepspeed训练时遇到不少问题，例如：
```

INFO:root:update index for ./output/dataset_file_0_dupe_factor_0-train.record finish
INFO:root:load dataset to memory...
Traceback (most recent call last):
  File "train.py", line 187, in <module>
    dataset_loader_filter_fn=dataset_loader_filter_fn if not with_record_iterable_dataset else None)
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/deep_training/data_helper/data_helper.py", line 475, in load_random_sampler
    pin_memory=pin_memory,**kwargs)
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 108, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

```

**Comment by ssbuild** [comment]
> 

没正确生成数据 ， rm -rf output  重新制作数据

**Comment by paulcx** [comment]
的确work，建议后面有空话加个数据集的验证。
目前，deepspeed在单机8卡上已经跑起来了，不过速度比单卡训练慢一倍。参数还没有调，不知道是什么问题。

**Comment by galaxyFloating** [comment]
> 的确work，建议后面有空话加个数据集的验证。 目前，deepspeed在单机8卡上已经跑起来了，不过速度比单卡训练慢一倍。参数还没有调，不知道是什么问题。

能问下是全层参数ft的吗？
另外能问问是否8卡都差不多一样的占用量，大概多大呀

**Comment by paulcx** [comment]
> > 的确work，建议后面有空话加个数据集的验证。 目前，deepspeed在单机8卡上已经跑起来了，不过速度比单卡训练慢一倍。参数还没有调，不知道是什么问题。
> 
> 
> 
> 能问下是全层参数ft的吗？
> 
> 另外能问问是否8卡都差不多一样的占用量，大概多大呀

是的，占用量差不多，取决于bs是多少。

**Comment by coder-yzh** [comment]
> > > 的确work，建议后面有空话加个数据集的验证。 目前，deepspeed在单机8卡上已经跑起来了，不过速度比单卡训练慢一倍。参数还没有调，不知道是什么问题。
> > 
> > 
> > 能问下是全层参数ft的吗？
> > 另外能问问是否8卡都差不多一样的占用量，大概多大呀
> 
> 是的，占用量差不多，取决于bs是多少。

您好，您的bs设置的是多少啊，我bs设置为4，layer层数为28报oom，想保留层数的不动
