### ISSUE TITLE
最新更新的代码出现的问题

### ISSUE THREAD

**Issue by paulcx** [ssbuild/chatglm_finetuning#62]
更新到[efaf1dd](https://github.com/ssbuild/chatglm_finetuning/commit/efaf1dd450774120d36bc074b056342aa41c1ec3)，出现问题：
```
  File "/workspace/xx/chatglm_finetuning/data_utils.py", line 219, in collate_fn
    return function(data, *args, **kwargs)
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
        context_length = input_ids.tolist().index(self.sptoken[-1]) + 1context_length = input_ids.tolist().index(self.sptoken[-1]) + 1

ValueErrorValueError: : 150004 is not in list    
150004 is not in listdata = self._next_data()
```

怀疑是和最新版本的chatglm 6b代码更新有关？

**Comment by ssbuild** [comment]
感谢提出问题，已修复，请测试。

**Comment by paulcx** [comment]
更新了，还是有问题：
```
...
File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/workspace/xx/chatglm_finetuning/data_utils.py", line 219, in collate_fn
    context_length = input_ids.tolist().index(self.sptoken[-1]) + 1
ValueError: 150004 is not in list
```

**Comment by ssbuild** [comment]
的确，try it now.

**Comment by paulcx** [comment]
一样的错误，没变。

**Comment by ssbuild** [comment]
@paulcx 
rm -rf output ， 因为有缓存，所以没做缓存数据

**Comment by paulcx** [comment]
```
INFO:root:update index for ./output/dataset_file_0_dupe_factor_0-train.record finish                                                                                                                                     
INFO:root:load dataset to memory...                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                       
  File "train.py", line 200, in <module>                                                                                                                                                                                 
    dataset_loader_filter_fn=dataset_loader_filter_fn if not with_record_iterable_dataset else None)                                                                                                                     
  File "/workspace/xx/chatglm_finetuning/deep_training/data_helper/data_helper.py", line 475, in load_random_sampler                                                                                                     
    pin_memory=pin_memory,**kwargs)                                                                                                                                                                                      
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 344, in __init__                                                                                                    
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]                                                                                                                                      
  File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 108, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
清了文件夹重新跑，结果又出现这个问题

**Comment by ssbuild** [comment]
> ```
> INFO:root:update index for ./output/dataset_file_0_dupe_factor_0-train.record finish                                                                                                                                     
> INFO:root:load dataset to memory...                                                                                                                                                                                      
> Traceback (most recent call last):                                                                                                                                                                                       
>   File "train.py", line 200, in <module>                                                                                                                                                                                 
>     dataset_loader_filter_fn=dataset_loader_filter_fn if not with_record_iterable_dataset else None)                                                                                                                     
>   File "/workspace/xx/chatglm_finetuning/deep_training/data_helper/data_helper.py", line 475, in load_random_sampler                                                                                                     
>     pin_memory=pin_memory,**kwargs)                                                                                                                                                                                      
>   File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 344, in __init__                                                                                                    
>     sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]                                                                                                                                      
>   File "/opt/conda/envs/accelerate/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 108, in __init__
>     "value, but got num_samples={}".format(self.num_samples))
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> ```
> 
> 清了文件夹重新跑，结果又出现这个问题

清除之后 ，需要重新制作特征数据， 检查数据是否制作成功。

**Comment by paulcx** [comment]
可以了，不知道是不是用多torchrun多卡参数启动脚本的时候，生成的数据有问题所以报错。总之，单卡启动自动生成数据集就可以跑。接着再用启动多卡训练也可以了。
