### ISSUE TITLE
THUDM / chatglm-6b-int4 加载时报错

### ISSUE THREAD

**Issue by Chtholly1** [ssbuild/chatglm_finetuning#64]
大佬，我用的不是THUDM / chatglm-6b，而是THUDM / chatglm-6b-int4，这在模型加载的时候会报错，请问改哪个地方可以解决？

Traceback (most recent call last):
  File "/home/guozitao/projects/chatglm_finetuning/train.py", line 164, in <module>
    model = MyTransformer(config=config, model_args=model_args, training_args=training_args,lora_args=lora_args)
  File "/home/guozitao/projects/chatglm_finetuning/train.py", line 26, in __init__
    super(MyTransformer, self).__init__(*args, **kwargs)
  File "/home/guozitao/anaconda3/lib/python3.9/site-packages/deep_training/nlp/models/transformer.py", line 280, in __init__
    self.set_model(self.__BACKBONE_CLASS__[0](*args, **kwargs))
  File "/home/guozitao/anaconda3/lib/python3.9/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1316, in __init__
    self.set_model(self.from_pretrained(ChatGLMForConditionalGeneration, *args, **kwargs))
  File "/home/guozitao/anaconda3/lib/python3.9/site-packages/deep_training/nlp/models/transformer.py", line 207, in from_pretrained
    cls_ = CLS.from_pretrained(
  File "/home/guozitao/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/guozitao/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2844, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.layers.0.attention.query_key_value.weight: copying a param with shape torch.Size([12288, 2048]) from checkpoint, the shape in current model is torch.Size([12288, 4096]).
	size mismatch for transformer.layers.0.attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for transformer.layers.0.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([16384, 2048]) from checkpoint, the shape in current model is torch.Size([16384, 4096]).
	size mismatch for transformer.layers.0.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 8192]) from checkpoint, the shape in current model is torch.Size([4096, 16384]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by ssbuild** [comment]
参考 #83

**Comment by Chtholly1** [comment]
> 参考 #83

谢谢

**Comment by code-8888** [comment]
你好 这个你解决了吗 我没太看懂那个issue 代码那行要加在哪里 我是拉了一个chatglm拉了一个chatglm-int4代码 用的本地路径 跟你的报错一样

```
tokenizer = AutoTokenizer.from_pretrained("../chatglm", trust_remote_code=True)
model = AutoModel.from_pretrained("../chatglm-int4", trust_remote_code=True).float()
model = model.eval()
```

**Comment by 714267807** [comment]
大佬，我用的不是THUDM / chatglm-6b，而是THUDM / chatglm-6b-int4，这在模型加载的时候会报错，请问改哪个地方可以解决？
我输入这个的时候
model=AutoModel.from_pretrained("D:\\data\\llm\\chatglm-6b-int4", trust_romote_code=True, revision="").half().cuda()
报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\transformers\models\auto\configuration_auto.py", line 899, in from_pretrained
    raise ValueError(
ValueError: Loading D:\data\llm\chatglm-6b-int4 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**Comment by ssbuild** [comment]
我看你是用官方，移步官方仓库下提问 @714267807
