### ISSUE TITLE
infer failed

### ISSUE THREAD

**Issue by liuxiaocs7** [ssbuild/chatglm_finetuning#7]
```
TrainingArguments(optimizer='lion', scheduler_type='linear', scheduler=None, adv={'mode': None, 'emb_name=': 'embedding', 'attack_iters': 2, 'minibatch_replays': 2, 'alpha': 0.1, 'epsilon': 1.0}, hierarchical_position=None, learning_rate=5e-05, learning_rate_for_task=5e-05, max_epochs=3, max_steps=-1, optimizer_betas=(0.9, 0.999), adam_epsilon=1e-08, gradient_accumulation_steps=1, max_grad_norm=1.0, weight_decay=0, warmup_steps=0, train_batch_size=4, eval_batch_size=2, test_batch_size=2, seed=42)
ModelArguments(model_name_or_path='/home/han/lx/ChatGLM-6B/chatglm-6b', model_type='chatglm', config_overrides=None, config_name='./config/config_small.json', tokenizer_name='/home/han/lx/ChatGLM-6B/chatglm-6b', cache_dir=None, do_lower_case=False, use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
Loading checkpoint shards: 100%|???????????????????????????????????????????????????????????????????????????????????????????????????????| 8/8 [01:19<00:00,  9.97s/it]
Traceback (most recent call last):
  File "/home/han/lx/chatglm_finetuning/infer.py", line 47, in <module>
    base_model.half().quantize(4).to(torch.device('cuda:0'))
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1195, in quantize
    self.transformer = quantize(self.transformer, bits)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/deep_training/nlp/models/chatglm/quantization.py", line 147, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/deep_training/nlp/models/chatglm/quantization.py", line 130, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/deep_training/nlp/models/chatglm/quantization.py", line 71, in compress_int4_weight
    kernels.int4WeightCompression(
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 48, in __call__
    func = self._prepare_func()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/kernels/base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/device/__init__.py", line 152, in use
    self._device.use()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/device/__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "/home/han/anaconda3/envs/lx_chatglm/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized
```

**Comment by ssbuild** [comment]
根据经验应该是显存不足

**Comment by liuxiaocs7** [comment]
> 根据经验应该是显存不足

您好，我的环境是3080，跑官方 `INT8` 的 `web_demo.py`可以跑起来，请问下为什么本项目(参数都是默认的)的推理显存不足？

```
ModelArguments(model_name_or_path='/home/han/lx/ChatGLM-6B/chatglm-6b', model_type='chatglm', config_overrides=None, config_name='./config/config_small.json', tokenizer_name='/home/han/lx/ChatGLM-6B/chatglm-6b', cache_dir=None, do_lower_case=False, use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
```

**Comment by ssbuild** [comment]
请参考 https://github.com/pytorch/pytorch/issues/3996

**Comment by liuxiaocs7** [comment]
> @liuxiaocs7
> 
> 请参考 [pytorch/pytorch#3996](https://github.com/pytorch/pytorch/issues/3996)

Thansk for you advice. `sudo rm -rf ~/.nv` seems not works for me. But i ran `python train.py` successfully，and memory usage is `9631MiB / 10014MiB`, so it may be a lack of memory according the issue above, i'll try on another gpu tomorrow.
