### ISSUE TITLE
执行data_utils.py抛出No module named 'tokenization_chatglm'

### ISSUE THREAD

**Issue by wjh177** [ssbuild/chatglm_finetuning#98]
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpajzcjpw0
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpajzcjpw0/_remote_module_non_scriptable.py
2023-03-29 03:00:02.988753: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-29 03:00:02.989255: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-29 03:00:02.989286: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
Traceback (most recent call last):
  File "/content/chatglm_finetuning/data_utils.py", line 23, in <module>
    from data_processer import DataStrategy, TokenTruncation, TokenSingleSliding, TokenDoubleSliding
  File "/content/chatglm_finetuning/data_processer.py", line 7, in <module>
    from models import ChatGLMTokenizer
  File "/content/chatglm_finetuning/models/__init__.py", line 9, in <module>
    from tokenization_chatglm import ChatGLMTokenizer
ModuleNotFoundError: No module named 'tokenization_chatglm'

**Comment by wjh177** [comment]
是否是早上的更新动到了 昨晚还是正常的

**Comment by ssbuild** [comment]
是的，把该部分移动到models模块， 确实容易出现找不到模块，撤回来了。

**Comment by Traceve** [comment]
最新拉的还是有这个问题呢？
Traceback (most recent call last):
  File "/data1/AILab/chatglm_finetuning/train.py", line 14, in <module>
    from data_utils import NN_DataHelper, train_info_args, get_deepspeed_config
  File "/data1/AILab/chatglm_finetuning/data_utils.py", line 23, in <module>
    from data_processer import DataStrategy, TokenTruncation, TokenSingleSliding, TokenDoubleSliding
  File "/data1/AILab/chatglm_finetuning/data_processer.py", line 7, in <module>
    from models import ChatGLMTokenizer
  File "/data1/AILab/chatglm_finetuning/models/__init__.py", line 9, in <module>
    from tokenization_chatglm import ChatGLMTokenizer
ModuleNotFoundError: No module named 'tokenization_chatglm'
